apiVersion: v1
kind: Service
metadata:
  name: swagger-api-service
  namespace: default
  labels: {
    "type" : "server",
    "env" : "multi"
  }
spec:
  selector:
    component: swagger-api
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
